// Generated by LiveScript 1.3.1
(function(){
  var mount, koaRouter, controller, router;
  mount = require('koa-mount');
  koaRouter = require('koa-router');
  controller = require('../controllers/home_controller');
  router = new koaRouter();
  router.get(/^\/$/, controller.index.get);
  module.exports = router;
}).call(this);
