// Generated by LiveScript 1.3.1
(function(){
  var path, express, app;
  path = require('path');
  express = require('express');
  app = express();
  app.enable("case sensitive routing");
  app.set("views", path.join(__dirname, "../views"));
  app.set("view engine", "hjs");
  app.set("layout", "partials/_layout");
  app.use(express['static'](path.join(__dirname, "../public")));
  app.engine("hjs", require("hogan-express"));
  app.use('/', function(req, res, next){
    return res.render('home/index', {});
  });
  module.exports = app;
}).call(this);
